### ISSUE TITLE
[BUG] Metric Temperature Bug when switching scenes

### ISSUE THREAD

**Issue by apoapostolov** [LeafWulf/smallweather#2]
SmallWeather 0.0.7. When changing scenes, even if weather is set to Metric, the symbol *C will switch to F.

**Comment by apoapostolov** [comment]
Seems to be a bigger bug. Not just the symbols change, but also data changes to an older previous data on scene changes.

**Comment by paulo-roger** [comment]
I will release the bugfix in a few minutes

**Comment by paulo-roger** [comment]
Thanks for the report, good catch!

**Comment by paulo-roger** [comment]
> Seems to be a bigger bug. Not just the symbols change, but also data changes to an older previous data on scene changes.

Yeah, now I see that, the first part is fixed now, this second is a bit tricky now

**Comment by paulo-roger** [comment]
Found it! I will release a new fix in a few minutes
