### ISSUE TITLE
[BUG]  Basic PreviewWeather - undefined (reading 'startingMonth')

### ISSUE THREAD

**Issue by Hydroxi** [LeafWulf/smallweather#3]
**Module Version:** v0.0.8

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

[log.log](https://github.com/LeafWulf/smallweather/files/10020729/log.log)

**Describe the bug**
Basic PreviewWeather - undefined (reading 'startingMonth')

**To Reproduce**
Open smallweather
Click Preview
nothing happens

Advanced Preview is working as expected!

**Expected behavior**
Should display the preview weather

**Screenshots**

**Browser:**
chrome 

**Foundry Version:** 
latest

**Game System:** 
5e

**Additional context**

i think in climate.js:20  the object currentSeason has no "icon" property:
```
 date: `2020-${climate.seasons[currentSeason.icon].startingMonth}-${climate.seasons[currentSeason.icon].startingDay}`,
```
climate object:
```
{
    "representativeLocation": "Siglufjörður",
    "seasons": {
        "summer": {
            "startingDay": "20",
            "startingMonth": "06"
        },
        "fall": {
            "startingDay": "21",
            "startingMonth": "09"
        },
        "winter": {
            "startingDay": "20",
            "startingMonth": "12"
        },
        "spring": {
            "startingDay": "19",
            "startingMonth": "03"
        }
    }
}
```

currentSeason object:
```
{
    "id": "888a1670",
    "name": "Winter",
    "startingMonth": 17,
    "startingDay": 19,
    "color": "#f2f8ff",
    "sunriseTime": 21600,
    "sunsetTime": 64800
}
```

**Comment by paulo-roger** [comment]
Hi! I appreciate this very complete bug report, I am already investigating the issue and hopefully will release an update soon.

Thanks.

**Comment by paulo-roger** [comment]
Please, which version of Simple Calendar are you using?

**Comment by Hydroxi** [comment]
And that was the question of questions...
Seems my Calendar Version was stucked. Had v1.3.75 installed and there was no update.

Did a Backup of my calendar, deleted it and reinstalled the latest v2.1.58.
Had to reconfigure the calendar and it works now!
Sorry for the inconvenience.

**Comment by paulo-roger** [comment]
no worries my friend, if you have any new issues, or suggestions do not hesitate to open a new report
