### ISSUE TITLE
Weather Icon is not showing properly

### ISSUE THREAD

**Issue by SesuUisu** [LeafWulf/smallweather#6]
Weather Icon is not showing properly:

![image](https://user-images.githubusercontent.com/5831548/204036242-0dede45d-1019-4441-8bf0-84eb512dc313.png)
![Screenshot 2022-11-25 185915](https://user-images.githubusercontent.com/5831548/204036556-902c81a8-9208-4454-a9b3-e4c0de7badbb.jpg)

**Comment by paulo-roger** [comment]
Thanks for the report!
I will look into this right now

**Comment by paulo-roger** [comment]
I am not able to reproduce the bug so far, just to make sure, are you on the latest version (0.0.8)?

**Comment by SesuUisu** [comment]
Sorry, I haven't checked if it's up-to-date. It happened on 0.0.6
With 0.0.8 it shows: 
![image](https://user-images.githubusercontent.com/5831548/204107724-4561600e-c75f-43b8-a407-1b2101bc117d.png)

**Comment by paulo-roger** [comment]
Cool!
