### ISSUE TITLE
Issues with API fetch

### ISSUE THREAD

**Issue by KuntaoDaChump** [LeafWulf/smallweather#7]
Not sure how this issue started popping up. Removing the module doesnt work, because when I re-download it, the module remembers all the data from before. I cant remove it completely and retry from the start. Removing it and restarting foundry doesnt work either. Also regenerating a new API reproduces the issue as well. This popup box keeps appearing whenever I change time. 
![Capture](https://user-images.githubusercontent.com/74020463/206546883-2e4e9857-de5a-4129-b0dd-2b77d5f319a4.PNG)

**Comment by KuntaoDaChump** [comment]
I feel like I found the issue, somehow I went above the free credit limit lol, thats crazy, I dont even know how haha. I'll try tomorrow, but I have a good feeling thats what it was.

**Comment by paulo-roger** [comment]
I am implementing a better way to work with the API, issues like these should happen less times.
